# Generated by Django 3.1.4 on 2021-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=10)),
                ('courseTitle', models.CharField(max_length=50)),
                ('courseDescription', models.TextField()),
                ('courseHours', models.CharField(max_length=25)),
                ('academicCredit', models.CharField(max_length=10)),
                ('calendarReference', models.TextField()),
            ],
        ),
    ]
