# Generated by Django 3.0.2 on 2021-01-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutlines',
            fields=[
                ('courseNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='academicCredit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='calendarReference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='courseDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='courseHours',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='courseTitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcomeNumber', models.CharField(blank=True, max_length=2)),
                ('outcomeDescription', models.TextField(blank=True)),
                ('graduateAttribute', models.CharField(blank=True, max_length=50)),
                ('instructionLevel', models.CharField(blank=True, max_length=15)),
                ('courseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CourseOutlines')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGradesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(blank=True, max_length=25)),
                ('outcomes', models.CharField(blank=True, max_length=15)),
                ('weight', models.CharField(blank=True, max_length=3)),
                ('courseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CourseOutlines')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGradesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('letterAPlus', models.CharField(blank=True, max_length=4)),
                ('letterA', models.CharField(blank=True, max_length=4)),
                ('letterAMinus', models.CharField(blank=True, max_length=4)),
                ('letterBPlus', models.CharField(blank=True, max_length=4)),
                ('letterB', models.CharField(blank=True, max_length=4)),
                ('letterBMinus', models.CharField(blank=True, max_length=4)),
                ('letterCPlus', models.CharField(blank=True, max_length=4)),
                ('letterC', models.CharField(blank=True, max_length=4)),
                ('letterCMinus', models.CharField(blank=True, max_length=4)),
                ('letterDPlus', models.CharField(blank=True, max_length=4)),
                ('letterD', models.CharField(blank=True, max_length=4)),
                ('letterF', models.CharField(blank=True, max_length=4)),
                ('courseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CourseOutlines')),
            ],
        ),
        migrations.AlterField(
            model_name='calenderinfo',
            name='courseNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CourseOutlines'),
        ),
    ]
