# Generated by Django 3.1.4 on 2021-01-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderinfo',
            name='courseTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='graduateattribute',
            name='outcomeNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
