# Generated by Django 3.1.4 on 2021-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210112_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcomeNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
