# Generated by Django 3.1.5 on 2021-01-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210104_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseOutlines',
            new_name='CourseOutline',
        ),
        migrations.RenameModel(
            old_name='LearningOutcomes',
            new_name='LearningOutcome',
        ),
    ]
